return (async () => {
  const run = Zotero.ZoteroTTSRun, state = run.state, baseline = state.baseline || {}, p = Services.prefs, sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
  const fixtures = state.fixtures || {}, ids = []; for (const kind of ['pdf', 'epub']) if (fixtures[kind]?.itemID) ids.push(fixtures[kind].itemID);
  const closed = [], errors = [];
  for (const id of ids) for (const r of Zotero.Reader?._readers || []) if (r?.itemID === id) { try { r._internalReader?.toggleReadAloudPopup(false); } catch (e) { errors.push('popup ' + id + ': ' + String(e)); } try { const pending = r.close?.(); if (pending?.then) await pending; closed.push({ id, tabID: r.tabID }); } catch (e) { errors.push('close ' + id + ': ' + String(e)); } }
  for (let t = 0; t < 180; t++) { let present = false; for (const r of Zotero.Reader?._readers || []) if (ids.includes(r?.itemID)) present = true; if (!present) break; await sleep(50); }
  const erased = []; for (const id of ids) { try { const item = Zotero.Items.get(id); if (item) { await item.eraseTx(); erased.push({ id, erased: !Zotero.Items.get(id) }); } } catch (e) { errors.push('erase ' + id + ': ' + String(e)); } }
  const write = (name, saved) => { if (!saved || !saved.user) { if (p.prefHasUserValue(name)) p.clearUserPref(name); return; } if (saved.type === p.PREF_STRING) p.setStringPref(name, String(saved.value)); else if (saved.type === p.PREF_BOOL) p.setBoolPref(name, !!saved.value); else if (saved.type === p.PREF_INT) p.setIntPref(name, Number(saved.value)); };
  const prefNames = Object.keys(baseline.prefs || {}), memoryName = 'extensions.zotero.zotero-tts.readAloud.memory', voicesName = 'extensions.zotero.reader.readAloudVoices';
  for (const name of prefNames) if (name !== memoryName && name !== voicesName) write(name, baseline.prefs[name]);
  if (baseline.prefs[voicesName]) write(voicesName, baseline.prefs[voicesName]);
  if (baseline.prefs[memoryName]) write(memoryName, baseline.prefs[memoryName]);
  if (baseline.selectedTabID) for (const r of Zotero.Reader?._readers || []) if (r?.tabID === baseline.selectedTabID) { try { Zotero_Tabs.select(baseline.selectedTabID); } catch (e) {} break; }
  const prefWin = Services.wm.getMostRecentWindow('zotero:pref'); if (prefWin) { prefWin.close(); for (let i = 0; i < 100 && Services.wm.getMostRecentWindow('zotero:pref'); i++) await sleep(50); }
  await sleep(700);
  const read = name => { const type = p.getPrefType(name), user = p.prefHasUserValue(name); let value = null; try { if (type === p.PREF_STRING) value = p.getStringPref(name); else if (type === p.PREF_BOOL) value = p.getBoolPref(name); else if (type === p.PREF_INT) value = p.getIntPref(name); } catch (e) {} return { type, user, value }; };
  const finalPrefs = {}, mismatches = [], defaultDrift = []; for (const name of prefNames) { const now = read(name), before = baseline.prefs[name]; finalPrefs[name] = /readAloud\.memory$|reader\.readAloudVoices$/.test(name) ? { type: now.type, user: now.user, present: typeof now.value === 'string' && now.value.length > 0, chars: typeof now.value === 'string' ? now.value.length : null } : now; if (before && (now.user !== before.user || now.value !== before.value)) { const expectedDefaultChange = name === 'extensions.zotero.zotero-tts.readAloud.playerLayout' && !before.user && !now.user; if (expectedDefaultChange) defaultDrift.push({ name, before: before.value, after: now.value, user: false, reason: 'in-place candidate default changed from retained A to top while user flag stayed false' }); else mismatches.push({ name, before: /readAloud\.memory$|reader\.readAloudVoices$/.test(name) ? { chars: String(before.value || '').length } : before.value, after: /readAloud\.memory$|reader\.readAloudVoices$/.test(name) ? { chars: String(now.value || '').length } : now.value, user: { before: before.user, after: now.user } }); } }
  const fixtureReaders = []; for (const r of Zotero.Reader?._readers || []) if (ids.includes(r?.itemID)) fixtureReaders.push(r.itemID); const fixtureAudit = {}; for (const kind of ['pdf', 'epub']) { const id = fixtures[kind]?.itemID || null; let exists = false; try { exists = !!id && !!Zotero.Items.get(id); } catch (e) {} fixtureAudit[kind] = { id, exists }; }
  const nowErrors = Zotero.getErrors?.(), list = Array.isArray(nowErrors) ? nowErrors.map(String) : [String(nowErrors ?? '')], oldErrors = baseline.errors || [], newRelevant = list.filter(x => /zotero-tts|dead object/i.test(x) && !oldErrors.includes(x)).map(x => x.slice(0, 300));
  const owner = []; for (const before of baseline.readers || []) { let current = null; for (const r of Zotero.Reader?._readers || []) if (r?.itemID === before.itemID && r?.tabID === before.tabID) { current = r; break; } const m = current?._internalReader?._readAloudManager; const now = current ? { itemID: current.itemID, tabID: current.tabID, active: !!m?.active, paused: !!m?.paused, popupOpen: !!m?.popupOpen || !!current?._internalReader?._state?.readAloudState?.popupOpen, position: m?._controller?._position ?? null, voice: m?.selectedVoiceID || null, tier: m?._selectedTier || null } : null; owner.push({ before, now, equal: !!now && ['itemID', 'tabID', 'active', 'paused', 'popupOpen', 'position', 'voice', 'tier'].every(k => now[k] === before[k]) }); }
  if (errors.length || mismatches.length || fixtureReaders.length || Object.values(fixtureAudit).some(x => x.exists)) throw new Error('cleanup failed: ' + JSON.stringify({ errors, mismatches, fixtureReaders, fixtureAudit }));
  if (!baseline.debugStoring) try { Zotero.Debug.setStore(false); } catch (e) { errors.push('debug restore: ' + String(e)); }
  const out = { closed, erased, errors, mismatches, defaultDrift, fixtureReaders, fixtureAudit, finalPrefs, owner, ownersPass: owner.every(x => x.equal), newRelevantErrors: newRelevant, selectedTabID: globalThis.Zotero_Tabs?.selectedID || null, settingsOpen: !!Services.wm.getMostRecentWindow('zotero:pref'), debugStoring: !!Zotero.Debug?.storing };
  state.cleanup = out; return JSON.stringify(out, null, 1);
})()
